#include "sfz_writer.h"
#include <stdio.h>
#include <string.h>

/* ---------- helpers ---------- */

static const char *note_names[] = {
    "C", "Cs", "D", "Ds", "E", "F", "Fs", "G", "Gs", "A", "As", "B"
};

/* Convert MIDI note number to a human-readable string like "C2", "Fs3".
   Result is written into buf (must be >= 8 bytes). */
static void midi_note_name(int note, char *buf, int buf_size)
{
    if (note < 0)   note = 0;
    if (note > 127) note = 127;
    int octave = (note / 12) - 1;
    int pc     = note % 12;
    snprintf(buf, buf_size, "%s%d", note_names[pc], octave);
}

/* Find sample in inst->samples[] matching the given note and velocity.
   Returns pointer or NULL. */
static const sfz_sample_info_t *find_sample(const sfz_instrument_t *inst,
                                             int midi_note, int velocity)
{
    for (int i = 0; i < inst->sample_count; i++) {
        if (inst->samples[i].midi_note == midi_note &&
            inst->samples[i].velocity  == velocity) {
            return &inst->samples[i];
        }
    }
    return NULL;
}

/* ---------- public API ---------- */

int sfz_write(const char *path, const sfz_instrument_t *inst)
{
    if (!path || !inst) return -1;

    FILE *f = fopen(path, "w");
    if (!f) return -1;

    const int N = inst->num_zones;
    const int M = inst->num_layers;

    /* --- header --- */
    fprintf(f, "// Generated by Sample Robot\n");
    fprintf(f, "// %s - %d zones, %d velocity layers\n\n",
            inst->instrument_name, N, M);

    fprintf(f, "<control>\n");
    fprintf(f, "default_path=samples/\n\n");

    fprintf(f, "<global>\n");
    fprintf(f, "ampeg_release=0.5\n\n");

    /* --- precompute velocity midpoints --- */
    int vel_mid[SFZ_MAX_LAYERS]; /* vel_mid[i] = midpoint between layer i and i+1 */
    for (int j = 0; j < M - 1; j++) {
        vel_mid[j] = (inst->sample_velocities[j] + inst->sample_velocities[j + 1]) / 2;
    }

    /* --- per-zone groups --- */
    for (int i = 0; i < N; i++) {
        int note = inst->sample_notes[i];

        /* Compute key range boundaries */
        int lokey, hikey;

        if (N == 1) {
            lokey = inst->range_low;
            hikey = inst->range_high;
        } else if (i == 0) {
            /* First zone */
            int half = (inst->sample_notes[1] - note) / 2;
            lokey = note - half;
            if (lokey < 0) lokey = 0;
            int mid_next = (note + inst->sample_notes[1]) / 2;
            hikey = mid_next;
        } else if (i == N - 1) {
            /* Last zone */
            int mid_prev = (inst->sample_notes[i - 1] + note) / 2;
            lokey = mid_prev + 1;
            int half = (note - inst->sample_notes[i - 1]) / 2;
            hikey = note + half;
            if (hikey > 127) hikey = 127;
        } else {
            /* Middle zone */
            int mid_prev = (inst->sample_notes[i - 1] + note) / 2;
            int mid_next = (note + inst->sample_notes[i + 1]) / 2;
            lokey = mid_prev + 1;
            hikey = mid_next;
        }

        /* Comment with note name */
        char name_buf[8];
        midi_note_name(note, name_buf, sizeof(name_buf));
        fprintf(f, "// --- Zone %d: %s (MIDI %d), keys %d-%d ---\n",
                i, name_buf, note, lokey, hikey);

        fprintf(f, "<group>\n");
        fprintf(f, "lokey=%d hikey=%d pitch_keycenter=%d\n\n",
                lokey, hikey, note);

        /* Per-velocity-layer regions */
        for (int j = 0; j < M; j++) {
            const sfz_sample_info_t *smp = find_sample(inst, note,
                                                        inst->sample_velocities[j]);
            if (!smp) continue;

            fprintf(f, "<region>\n");
            fprintf(f, "sample=%s\n", smp->filename);

            /* Velocity range and crossfade */
            if (M == 1) {
                fprintf(f, "lovel=1 hivel=127\n");
            } else if (j == 0) {
                /* Softest layer */
                fprintf(f, "lovel=1 hivel=%d\n", vel_mid[0]);
                fprintf(f, "xfout_lovel=%d xfout_hivel=%d\n",
                        inst->sample_velocities[0] + 1, vel_mid[0]);
            } else if (j == M - 1) {
                /* Loudest layer */
                fprintf(f, "lovel=%d hivel=127\n", vel_mid[M - 2]);
                fprintf(f, "xfin_lovel=%d xfin_hivel=%d\n",
                        vel_mid[M - 2], inst->sample_velocities[M - 1] - 1);
            } else {
                /* Middle layer */
                fprintf(f, "lovel=%d hivel=%d\n", vel_mid[j - 1], vel_mid[j]);
                fprintf(f, "xfin_lovel=%d xfin_hivel=%d\n",
                        vel_mid[j - 1], inst->sample_velocities[j] - 1);
                fprintf(f, "xfout_lovel=%d xfout_hivel=%d\n",
                        inst->sample_velocities[j] + 1, vel_mid[j]);
            }

            /* Loop opcodes */
            if (smp->has_loop) {
                fprintf(f, "loop_mode=loop_sustain\n");
                fprintf(f, "loop_start=%d\n", smp->loop_start);
                fprintf(f, "loop_end=%d\n", smp->loop_end);
                fprintf(f, "loop_crossfade=%d\n", smp->loop_crossfade);
            } else {
                fprintf(f, "loop_mode=no_loop\n");
            }

            fprintf(f, "\n");
        }
    }

    fclose(f);
    return 0;
}
